

CREATE TABLE IF NOT EXISTS jobs (
    job_id STRING,
    job_title STRING,
    employer_name STRING,
    employer_logo STRING,
    employer_website STRING,
    job_publisher STRING,
    job_employment_type STRING,
    job_employment_types ARRAY<STRING>,
    job_apply_link STRING,
    job_apply_is_direct BOOLEAN,
    apply_options ARRAY<MAP<STRING, STRING>>,
    job_description STRING,
    job_is_remote BOOLEAN,
    job_posted_at STRING,
    job_posted_at_timestamp BIGINT,
    job_posted_at_datetime_utc STRING,
    job_location STRING,
    job_city STRING,
    job_state STRING,
    job_country STRING,
    job_latitude DOUBLE,
    job_longitude DOUBLE,
    job_benefits ARRAY<STRING>,
    job_benefits_strings ARRAY<STRING>,
    job_google_link STRING,
    job_salary STRING,
    job_salary_string STRING,
    job_min_salary DOUBLE,
    job_max_salary DOUBLE,
    job_salary_period STRING,
    job_highlights MAP<STRING, ARRAY<STRING>>,
    job_onet_soc STRING,
    job_onet_job_zone STRING,
    employer_reviews MAP<STRING, STRING>,
    job_uid STRING
);